name: ci
on: [push]
jobs:
  tests:
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v1
    with:
      n: 3
      start: npm start

    runs-on: ubuntu-20.04
    steps:
      # capture screenshots, videos, Mochawesome reports
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Mochawesome
          path: cypress/results
