name: ci
on: [push]
jobs:
  single:
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v2
    with:
      start: npm start

  tests:
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with:
      n: 3
      start: npm start
