name: merge
on: [push]
jobs:
  merge-reports:
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v2
    with:
      nE2E: 3
      start: npm start
      # merge all test reports into one
      # https://github.com/bahmutov/cypress-workflows
      marge: true
